#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { Buffer } from 'node:buffer';

const parseArg = (name, fallback = '') => {
  const index = process.argv.indexOf(name);
  if (index === -1) {
    return fallback;
  }
  return process.argv[index + 1] || fallback;
};

const inputPath = parseArg('--input', '');
const outputPath = parseArg('--output', path.resolve('src/prompts/promptCatalog.enc.ts'));
const keyB64 =
  parseArg('--key', '') ||
  process.env.PROMPT_AES_KEY_B64 ||
  process.env.EXPO_PUBLIC_PROMPT_AES_KEY_B64;
const keyId =
  parseArg('--key-id', '') ||
  process.env.PROMPT_AES_KEY_ID ||
  process.env.EXPO_PUBLIC_PROMPT_AES_KEY_ID ||
  'prompt-key-v1';

if (!inputPath) {
  console.error('Missing --input. Example: node scripts/encrypt-prompts.mjs --input /tmp/prompts.json');
  process.exit(1);
}
if (!keyB64) {
  console.error('Missing AES key. Provide --key or set PROMPT_AES_KEY_B64 / EXPO_PUBLIC_PROMPT_AES_KEY_B64');
  process.exit(1);
}

const key = Buffer.from(keyB64, 'base64');
if (key.length !== 32) {
  console.error('Prompt AES key must decode to 32 bytes for AES-256-GCM');
  process.exit(1);
}

const inputJson = JSON.parse(fs.readFileSync(inputPath, 'utf8'));
const entries = Object.entries(inputJson);
if (entries.length === 0) {
  console.error('Input prompt map is empty');
  process.exit(1);
}

const encryptedCatalog = {};
for (const [promptId, templateText] of entries) {
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv('aes-256-gcm', key, iv);
  const ciphertext = Buffer.concat([cipher.update(String(templateText), 'utf8'), cipher.final()]);
  const tag = cipher.getAuthTag();

  encryptedCatalog[promptId] = {
    alg: 'AES-256-GCM',
    keyId,
    ivB64: iv.toString('base64'),
    tagB64: tag.toString('base64'),
    ciphertextB64: ciphertext.toString('base64'),
    ts: Date.now(),
  };
}

const output = `/* eslint-disable quotes, comma-dangle */\n// This file is generated by scripts/encrypt-prompts.mjs.\nconst promptCatalog = ${JSON.stringify(encryptedCatalog, null, 2)};\n\nexport default promptCatalog;\n`;
fs.mkdirSync(path.dirname(outputPath), { recursive: true });
fs.writeFileSync(outputPath, output, 'utf8');
console.log(`Encrypted ${entries.length} prompt templates -> ${outputPath}`);
