export const PROMPT_IDS = {
  DISPLAYSTORE_TEACHING_DATA: 'DISPLAYSTORE_TEACHING_DATA',
  DISPLAYSTORE_SCENE_IMAGE: 'DISPLAYSTORE_SCENE_IMAGE',
  DISPLAYSTORE_ELEMENT_IMAGE: 'DISPLAYSTORE_ELEMENT_IMAGE',
  DRAFT_NAMING_PLAN: 'DRAFT_NAMING_PLAN',
  DRAFT_LANGUAGE_PLAN: 'DRAFT_LANGUAGE_PLAN',
  DRAFT_DIALOG_PLAN: 'DRAFT_DIALOG_PLAN',
  DRAFT_PRONUN_PLAN: 'DRAFT_PRONUN_PLAN',
  THEME_SELECTION_INTEREST: 'THEME_SELECTION_INTEREST',
  THEME_SCENE_FALLBACK: 'THEME_SCENE_FALLBACK',
  GPT_LEARNING_SCENES: 'GPT_LEARNING_SCENES',
  GPT_LEARNING_SCENE_IMAGE: 'GPT_LEARNING_SCENE_IMAGE',
  GPT_LEARNING_REGEN_IMAGE: 'GPT_LEARNING_REGEN_IMAGE',
  GPT_TEST_DESCRIPTIONS: 'GPT_TEST_DESCRIPTIONS',
  PREF_REINFORCEMENT_IMAGE: 'PREF_REINFORCEMENT_IMAGE',
  PRONUN_GOAL: 'PRONUN_GOAL',
  PRONUN_WORDS4: 'PRONUN_WORDS4',
  PRONUN_WORD1: 'PRONUN_WORD1',
  PRONUN_PINYIN: 'PRONUN_PINYIN',
  PRONUN_WORD_IMAGE: 'PRONUN_WORD_IMAGE',
} as const;

export type PromptId = (typeof PROMPT_IDS)[keyof typeof PROMPT_IDS];
