/* eslint-disable quotes, comma-dangle */
// This file is generated by scripts/encrypt-prompts.mjs.
const promptCatalog = {
  "DISPLAYSTORE_TEACHING_DATA": {
    "alg": "AES-256-GCM",
    "keyId": "prompt-key-v1",
    "ivB64": "9d2ywyuxxrNtRQ1Y",
    "tagB64": "VH0sGNagqu//a1QkyI/gVg==",
    "ciphertextB64": "v7WbrS6lALY8AmAbdkFRnEvsQ+pNKouwd++LTyOvfHkz3/SPPQKNF1HjIOyhQp6DFUUg8USHYg/scolAB/W0qKlSR1+h6MJgeReatVNdaBlqZBezK1sjHt0Io5UZxkz6Uhlvkw28ENxrm18doaGx2noiQOBGx/fF0Ul2R0sZrYKljFE9zrDaaKQ35YjLyDbz03KxvR4oD7c7HQYFF9cU4kSDy3NP64mmNQbJyiRtVPCCZVdBBcPOwP4efh5fraKw/pbWTi/Ehob/7NpOV88mhcZRA5/o3564g9jMin1YIHI25lfkte0srv4RYMKEh12I+XDxWyjo7H6B/T5+LM/bUWsa+bsveuWpdotJVz7uQZ56WFoI9pd6vh1ICosPS2616f1p7BIZXyzHa83QB5HaVMla/TBmqoSWAL8uXT/xbDN2zVkMUyAtreZpHFNGi6n9NvYJSW6hAF5cpCpanAO+iKxG3+dtEmBlP4nGRl3DvdcPPB3ykTePwcHepYIjh2JCh4AeVNv+RgSItNun7HIW7h9c9R3L1bYf+9wxZhh4tsTTOVBZ42flAENmpkQGkEqJAwMUWI8PqDLk8nP+bPX1urUV5fD5d2QFswfn4Y/2nv2uP1qr+72c4ACcTHLHAnNOIz66ijc+RVq74h0DWXthqw==",
    "ts": 1772582264447
  },
  "DISPLAYSTORE_SCENE_IMAGE": {
    "alg": "AES-256-GCM",
    "keyId": "prompt-key-v1",
    "ivB64": "jZnfYYCq69jLnDOP",
    "tagB64": "H4uapi58e2ObUwr7i5Fk4w==",
    "ciphertextB64": "D+up8PhgBjOYBUttLreUyXsa453+tq59VpEVChv5FLnzmOs8YVVhA0qgvYoSRzjcxF6g4ihfrGJXgTu+dAVerFjZx31W7EVENRG2av5Scgq6re7zY5FE7YMf73eb/W1YSFnyXNEUny/q6ayNe7u/AB9rgwIx2+LjOmDGZM2jS+xZp/oAUYQOL3Pmp+nOanHc7yVxMYixQZPK068b85lsM17mnWUh7+HoPTTmlnMRun5Y8foeVM4H1PVIe8zmW7J6IOmCJXXBcQJnywpzeC386QrOyvv35tdr44mf6xHebmE1CDbXdzlX",
    "ts": 1772582264448
  },
  "DISPLAYSTORE_ELEMENT_IMAGE": {
    "alg": "AES-256-GCM",
    "keyId": "prompt-key-v1",
    "ivB64": "/yxoXm2hHLr4NTQ/",
    "tagB64": "YF42V1T09YunDh2eeG6AnA==",
    "ciphertextB64": "Y7pJ34N6W9a+s5lwjtYz+AlnCqGBC9LZTv8Tb79s1p1JCYOLPLrABpCF5rc8Rw7f5ytMgzwZ6KVWrSsd+Pua0Zr23ydmQtxufIu5ki79aIzo3xw8t6/5bT3W4SN6apM3WoiwkZpXWvtHIaAgxFA=",
    "ts": 1772582264448
  },
  "DRAFT_NAMING_PLAN": {
    "alg": "AES-256-GCM",
    "keyId": "prompt-key-v1",
    "ivB64": "B9++y3Q/l8v9hZ39",
    "tagB64": "N5slyG0f6EztmOiyF7k1Yw==",
    "ciphertextB64": "92arQINhCCI60APp9FLWiji8xiDtAN590UxLFrVcCElaBEjox7XJS450D8a7k2xqnVoEfACrzkbEDAbmpCyd1JHOA2OqhtofsCrIrCqgzZP7PclEkKEUXRZeoORRHK+fuJ55M2j9HjnjNND6EIujAEyl0odmukODtIdYUpJIVfPi5mCSqV0diYHNTq2VYRxYuauJnZs6FoV+FTfE0WbJyq7Z4nllfwDR1AuSpHFxNiEYLCzCA3n7f+KvHdrShF6j8QEzQYw1U6+Qx+eMz5/hw08qof2FZLF5kkzoCysytT1omMa8RVP7So+bbxbJ6botR1NKvgmlT2eqABvG+Zm2pRIjUEpl21d+RS5d/aN8cz+KOX8D40GTK+LUpj5FNyQjQjJrTRecTL83MAR5vdyYYfqqSJJ/ruLW4hYZiSAWo9wzrvRtHfwhSWL514qMCv06Ew1MeXPVcEbXTc7VQ0L9LdPG8Q==",
    "ts": 1772582264448
  },
  "DRAFT_LANGUAGE_PLAN": {
    "alg": "AES-256-GCM",
    "keyId": "prompt-key-v1",
    "ivB64": "KHRNSSHbXVGLGl26",
    "tagB64": "VBpvZY9ugMS7gAt53CGdKA==",
    "ciphertextB64": "Tgl4noG4V3U0MtBL7qdOSaoV4XH6MX8Z+2WIz0RKX9wN1Sx72TgNpABh93U7EhS47sfShJE3d54uEC9wOdQpp8WoeNt9L1O2pPYWKb8FcQXD4/9Me1zijwcAQkBFy3fWP+CjbDqE1E+yAs/GYgB9r4BtCluVYBjt+cgSxGWTkvzb6KmYmq+liXSLzHCPt1t7J6dqaZRbaUrIsAgZ96/BdhQlz6csIjYF6XwkHtz/FynmiAHlYCqsTW0BSngUeWmDeGc5qzQv9eiuavIOE84dpA/Ydrubk9ZXjlwpiLlip0VxwxaHhO5z5SeN4n7rQN37J+ZUpSvpdN53/PgSpmDAeJ3f0GoIFEzl/SEce6X5d23L0kPKEPFCyLxX7FzxWbpYroR5ReolPDilARl1jnu0AqkvVNBF",
    "ts": 1772582264448
  },
  "DRAFT_DIALOG_PLAN": {
    "alg": "AES-256-GCM",
    "keyId": "prompt-key-v1",
    "ivB64": "dby2woa/ubKoTULu",
    "tagB64": "NO4QzzW0OKq1A2azfZgqpw==",
    "ciphertextB64": "jeDbR7tnSVPm/YNYT5DMCzFh2J+bBTjk8YX7qQX11wWO9160sUcGpJbhOsj15mNUx/UdyUkJH2l+chUw80aGkipjvkm8TbeUtjwxt/h88hRWXd6oIlBRZblDi9xzlXOUk+Z6T1Bwu/3EtNSJSLL2Ais75HK09t8FZEFMpzWhdqP49FwaQJyYO7siqcwYsTW2aM30hfl1Osozg/GaAaymARyC24PDfUjfcUrRHx/fK89SdcA81XoUPvH/fh5jhKEjB3mkNqxQMaeGEypAbXCujSRbfNYPcdyr1wYwCZbM7OjMTN99XZB6aey7Nkhca+i9KRmeXwLH0sPqyq/urlslwjzg9hAvGRpd2XBohVCY/yRiiVBS8McXn8NcPfoQHeRO/ts52LKCA8PRSSqSbtcv",
    "ts": 1772582264448
  },
  "DRAFT_PRONUN_PLAN": {
    "alg": "AES-256-GCM",
    "keyId": "prompt-key-v1",
    "ivB64": "gxuCTu9u7HWtrpiy",
    "tagB64": "e7rau7bUrzWtD/lyw57Xww==",
    "ciphertextB64": "ugwJZTlu6GjWIxagy6I9TuNQoNYR14sOcz9Tw+wJnwXWVH/aWig+yiL6Ff7+BTNfZdYmzCvv2h+J/PlVjgBcAZwz4Pffqy3rWXZhyQXCjE4CWusu9qbyvaiqr4wJsPhFsLfw0A4Bahdaq0DmKFey4n8Rp19Voz5/+K1qPhs6pxK4Rh9d1TYoTU8MXppdSUW0BCR1rMYQbFBD/V0nSxoJ/b5W9IFDD7N4y4sqUV8bwsTKQoC/cVV0HUisqqpRFY5KGm/NoKNoGJtHj85EY4diPfAvMbOCEIaehu7ehC+XHFg9FcaB5qGSrz0EypAgb0PeS2tKUVq/X1OxG79NAH8kMH0z0RwdVQrIZOLeDY3ItNnPkko3q1304GcXFGAy9Z2BIokQ3NDMMGKb4hJf5Bkbzpo=",
    "ts": 1772582264448
  },
  "THEME_SELECTION_INTEREST": {
    "alg": "AES-256-GCM",
    "keyId": "prompt-key-v1",
    "ivB64": "9yFyOTzGqL9mYOD2",
    "tagB64": "gx0NigDuU1neI7/Q773pog==",
    "ciphertextB64": "M9u98DrvMxMhvHZ7TcNERsz7fWFTHNWs5M+eo9Pqe/usnc56lwODnO8elDAjy0dz85db64IbOzrziHhNVE1+NPho0Iex8kwrgZIw4BWTzDLu7G06E281lxbpqWO7X6aBr+QTIxp9u1PaUVCsn094S1cQLpzEB/AK4bC1/PqJfW07PBXjc16dM93bVE5QGoeo4XsaWzzGLqMJLjoe7VH37TyiM4nOg/FlDaJNezfdQhvu9sdUa8PToQnPuZXmjjVS",
    "ts": 1772582264448
  },
  "THEME_SCENE_FALLBACK": {
    "alg": "AES-256-GCM",
    "keyId": "prompt-key-v1",
    "ivB64": "h2LYVHRhmBYvGcGX",
    "tagB64": "QG+K9h040VUa7/sL4qLxrw==",
    "ciphertextB64": "mrgFuqPEnIbxoKe1SukkWbedvU0N82v4ozspL6X+589Z9/EWHUGpqJ7rsbk0c1WFyACujbiQqGfFr4YN9O8+bm8UL3fYmJ/0bXpTE33+fyu6t7G47UNoNg+EWXRLD68cT6QNsT1QTR1b/+WyJvcClXtf7m8idKIKbWEZliifuMC24gzcpFlaoFO9ZUZgJlf660wOvZpNQ32X",
    "ts": 1772582264448
  },
  "GPT_LEARNING_SCENES": {
    "alg": "AES-256-GCM",
    "keyId": "prompt-key-v1",
    "ivB64": "adl70AGKz3Tl/LQ5",
    "tagB64": "KUUgGO2sD8WpGgsyBfuJhQ==",
    "ciphertextB64": "75iIm+vRCBXSTazA7HDpl1kB5j1fUj3b+cL1ByCU+YCQIyg505FPSDFsaF5K7P3I1cbg8gU2gTCrhrqPpaFi",
    "ts": 1772582264448
  },
  "GPT_LEARNING_SCENE_IMAGE": {
    "alg": "AES-256-GCM",
    "keyId": "prompt-key-v1",
    "ivB64": "erqV1xE69maXInVx",
    "tagB64": "TRrnRa3bYVxsasAf6D+Wgw==",
    "ciphertextB64": "johXiSxr+7jwaqimtd9JFSHz8UsywS9/59dpu6UIGgV/EbtlKyU/pEyhaMUBF3e1hD9XIVjQEzs4HFwLVzIKk4aGz1tZL4a8GT7+dDrnjbQOKeOvfg2i6H/5vZ/lRCOS/6Ef3GDQycFbTx8Jc9v8PFMBI4DyuzyqJv/vhqACz49ymDGB3zKvEZ0e2CtwMHp6g6ng2Yul8AjVvU8AB+wlh3XgBKSv3Ke9QPVqeg==",
    "ts": 1772582264448
  },
  "GPT_LEARNING_REGEN_IMAGE": {
    "alg": "AES-256-GCM",
    "keyId": "prompt-key-v1",
    "ivB64": "ebJ3OH1kC1bq/sGo",
    "tagB64": "tr2thKaBvlnuG2N2Ms2PYg==",
    "ciphertextB64": "5Ay1/wkQntA2I6exLDkcaIxTOuQGcvT+XbKa8aiIU36KlEqdwgPuoyIvx1zRLChwZGJEV6OUJB+FWTNJdOWO2wW9m23MrT23mmUd",
    "ts": 1772582264448
  },
  "GPT_TEST_DESCRIPTIONS": {
    "alg": "AES-256-GCM",
    "keyId": "prompt-key-v1",
    "ivB64": "9Ro3veF9/ovpjtmH",
    "tagB64": "4FQVnvwo6M6faJ22UP8p8Q==",
    "ciphertextB64": "m+jsnB14K8pVVS16vj7hFGWz9QEkdI9VPcbigK1JD5AlaYkFUxjVhdE+e13lhjZUB0wWGBNS",
    "ts": 1772582264448
  },
  "PREF_REINFORCEMENT_IMAGE": {
    "alg": "AES-256-GCM",
    "keyId": "prompt-key-v1",
    "ivB64": "t9wmOUsMF1OENXnz",
    "tagB64": "WA/I+bknmBV7xnWuoFkAuA==",
    "ciphertextB64": "xXiyGvlmW9j7C06cGAmKaz5y5VbIw6l3Dq8FIFV6V4fiU/PGOqTis3nyliEJJOMIkJ5ynHlRLNzetyg3cWukXppDwhow5HjUKSvWNogbaHMyycCX3C9wKdqzybwx3KF2L2wfVmjcqQgv8K/MBuClhfAk1uvaFFwiMZ54tvScDRn6VyA35/YH4FChH3N0f38biAopU5X588k+kzlyg0K+Tdax5Q2VR9bG3gmKHMhH46IbtBxZ6BTrMzL4sirCRFBrMnfDY3F4IZNanMamuYMo54c0F9R3Hu9Zivx4xerYZcVrOCzxYPTDIfqPdJ1dZ89dOGxiZ/VK",
    "ts": 1772582264448
  },
  "PRONUN_GOAL": {
    "alg": "AES-256-GCM",
    "keyId": "prompt-key-v1",
    "ivB64": "9gUJ1zB+bRNvYdDT",
    "tagB64": "GkJqI6k/RqboTpr0MVJukg==",
    "ciphertextB64": "Im0wG2sNZXLUlmbi8FfZxPgI5eIfDlIBuy468NK+uhrke+dL7o8IDVMwFXYtEFJhMxeP0K/iPs1bHeIMAcweuOhHxCNfm8YlMETn9F9YbNdYA9lNMwM1lAJynTN4nh0tEDWBBmAP2L+c7G31EkGpsJ5ntL3EFR36MzHY4s5f7VRKFloEG0/XSbSZLDiRYmn93QxQk4WdGJpnkARs",
    "ts": 1772582264448
  },
  "PRONUN_WORDS4": {
    "alg": "AES-256-GCM",
    "keyId": "prompt-key-v1",
    "ivB64": "mNnfpPvWtZuL37UR",
    "tagB64": "rTrLCIbk7D+JLuNZ25JVLQ==",
    "ciphertextB64": "BBur9nK+PAUHHyKX0/xIa074/hIQDP1iNq+nt187IduK2BFp88GuKVfMlvtjUji0tquIqAbwsy2KqSrujrDBuS8bGCCmPfw3V0WcAwwkbLCsB0Fu/IklZnecZqGEIUkYegzpiAyMdJkffgua63LWcQixNKnwAM/TzAexzBe7LtakJ0osNg==",
    "ts": 1772582264448
  },
  "PRONUN_WORD1": {
    "alg": "AES-256-GCM",
    "keyId": "prompt-key-v1",
    "ivB64": "NZf9vx+ZwP/H2qNG",
    "tagB64": "TMrsvMHiYkmqqZM21SEn2Q==",
    "ciphertextB64": "kExQbJr8cIBMcXGLP1mcauvQpo8lI2Jn11UNNIK2s4KoaU04TzB3hpSh4/2lR/5MPNtX1CGXQvT1B3vcCJ7ZQ/C5xWN4epuZnXRKyh/7/hUr4pDtt3GW5gPwoo/x8J4xd3cSGDNLpc0YkpxRKNFpzJDGm+fu5IEnWLtdJUL7EdFlOS5Gyw==",
    "ts": 1772582264448
  },
  "PRONUN_PINYIN": {
    "alg": "AES-256-GCM",
    "keyId": "prompt-key-v1",
    "ivB64": "HklI6zqRXL0eQ1El",
    "tagB64": "x6NNLTlm8PrSu1iAHXIDGQ==",
    "ciphertextB64": "4RtGGYgoWfq8TajGeojceM4jnm1hlurbxooDIZDIUI6LqGsizpQWkG0gD7980NrPIsVWZRM7DIlK0Q8NtEXa2LoybNAJ/K0NPbu1MEn9R4uTqZ2DpWHe/pcYoQ5A",
    "ts": 1772582264448
  },
  "PRONUN_WORD_IMAGE": {
    "alg": "AES-256-GCM",
    "keyId": "prompt-key-v1",
    "ivB64": "I/tNYv43Y+g5GtNv",
    "tagB64": "6UsXnKOXETfTkdrvF6plPA==",
    "ciphertextB64": "TD394yud/Kbvz7D3wMP5pyfeUz98bPFCG8YflXDBDSiOvK4oOKEPWyFNZn/2SqzyLyTcatYioCs4IeS2GxHhXHG4/MuQWOggdAYqTPnZqrq+gpQUvgc=",
    "ts": 1772582264448
  }
};

export default promptCatalog;
